m-lab/locate

.travis.yml
README.md
handler/handler.go
locate.go
proxy/proxy.go
proxy/proxy_test.go

This change adds support to the /v2/query resource for returning real results based on a translated response from mlab-ns.
This change adds a new package `proxy` which returns the "Nearest" machines to the client by using the App Engine provided lat/lon and forwarding those parameters to mlab-ns.
Only v2/query/ndt/ndt5 and v2/query/ndt/ndt7  targets are currently supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/2)

Add real responses using proxy results from mlab-ns

---

management/README.md
management/create_encrypted_signer_key.sh
signer/load.go
signer/load_test.go

This change adds an operator script for creating and encrypting JWK signer keys. `create_encrypted_signer_key.sh`
This change adds a new package, `signer` for loading KMS encrypted private keys at runtime.
The combination of these two will provide support for the locate service to load a per-project JWK signer key at runtime and being issuing valid `access_tokens` in `/v2/query` replies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/3)

Add support for loading KMS encrypted, private JWK signer keys

---

api/v2/api.go
handler/handler.go
handler/monitoring.go
handler/monitoring_test.go
static/configs.go

This change makes the MonitoringResult type distinct from the QueryResult. A MonitoringResult instance has a single AccessToken and Target field. Both of these are better aligned with the needs of monitoring than the original QueryResult type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/6)

Create distinct MonitoringResult type

---

handler/handler.go
handler/handler_test.go
handler/monitoring_test.go
static/configs.go

This change simplifies how service URL templates are stored and formatted as keys in the QueryResult and MonitoringResult URLs objects.
Example of this can be found:
https://locate-dot-mlab-sandbox.appspot.com/v2/query/ndt/ndt5
https://locate-dot-mlab-sandbox.appspot.com/v2/query/ndt/ndt7
Note, that this results in the ndt5 ports in the key strings.
This change also simplifies how clients will register supported services with the locate service via heartbeat. i.e. (<service_i>=<url-template_j>)+.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/8)

Derive URL keys from url templates

---

app.yaml.mlab-ns
locate.go

This PR adds an app.yaml configuration for deployment to mlab-ns project (production).
As well, this change modifies the `/v2/query` path to `/v2beta1/query`. The path allows for final v2 breaking changes while still providing early access to the v2/query api in a production context. In part this to support https://github.com/ooni/probe-engine/issues/562
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/11)

Add production deployment config for locate/v2beta1

---

decrypt/load.go
locate.go
management/README.md

This change allows the configuration to specify multiple monitoring verifier keys. As well, this adds some documentation for key rotation, which requires support for multiple verify keys in the locate server as well as other services that verify access tokens, such as the ndt-server and access envelope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/13)

Add support for multiple verifier keys

---

cmd/monitoring-token/monitoring-token.go
handler/handler.go
handler/handler_test.go
proxy/proxy.go
proxy/proxy_test.go

This change sets the `Access-Control-Allow-Origin` response header to grant the widest permission for browsers to use the resources returned by the locate API.
Fixes https://github.com/m-lab/locate/issues/15
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/16)

Add CORS policy for /v2beta1/query handler

---

api/v2/api.go
handler/handler.go
handler/handler_test.go
handler/monitoring_test.go
proxy/proxy.go
proxy/proxy_test.go

This change adds a `Location` field to the `v2.Target` type to report the `city` and `country`  of the target server.
This change preserves some functionality provided by mlab-ns and requested by several early adopters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/18)

Add Location metadata to results

---

cloudbuild/app.yaml.mlab-ns
cloudbuild/app.yaml.mlab-sandbox
cloudbuild/app.yaml.mlab-staging
cloudbuild/cloudbuild.yaml
openapi.yaml
static/configs.go

This change adds the `endpoints_api_service` configuration to the app.yaml for the locate service.
This change also adds the `openapi.yaml` configuration that documents and specifies the Cloud Endpoints API that the locate service implements. Future development may be able to generate the openapi.yaml spec from the Go sources. However, because this combines the spec with documentation for the developer portal (e.g. https://api-portal.mlab-sandbox.measurementlab.net/ example of configuring a custom URL), this is a helpful starting point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/21)

Add openapi.yaml spec and enable endpoints for locate API

---

openapi.yaml

API key security was temporarily disabled pending complete HTTP referer patterns for one API key user. That is now complete. It should be safe to re-enable API key security, which this change does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/24)

Restore API key security

---

USAGE.md
api/v2/api.go
handler/handler.go
handler/handler_test.go

The previous type name was a legacy of the v2beta1 api which used the target resource name '/v2beta1/query'. However, that term is too generic. This change updates the result type to match the `/v2/nearest` resource name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/31)

Change type to NearestResult

---

api/locate/client.go
api/locate/client_test.go
handler/handler.go
handler/handler_test.go

This change adds a simple Go client package for the Locate API v2.
This is a simple client because it does not handle the Locate API `v2.NextRequest` response nor does it easily support the priority requests using API keys. This change makes it possible to migrate the ndt5-client-go and ndt7-client-go utilities to use access tokens by default and preserve existing functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/32)

Add locate client API package

---

handler/handler.go

This change explicitly sets a Cache-Control header to attempt to disable caching for some clients. Cached access tokens could lead to dysfunctional behavior such as multiple clients using the same tokens or clients receiving expired tokens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/36)

Attempt to disable caching

---

handler/handler.go

Suspecting that some Locate v2 responses are being cached, it would be helpful to log the protocol used to connect to the server, i.e. http or https. Caching can be performed by third parties only when http requests are used, or when middleboxes intercept https connections (mitm, which we would not detect using this logging).
If we see a high rate of http requests, then we could consider adding an option to disallow that request type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/37)

Log the client protocol used to contact the server

---

handler/handler.go
handler/handler_test.go
handler/monitoring.go

This change propagates some http parameters provided to the locate API request to the generated URLs so that they are passed to the measurement service.
Related to https://github.com/m-lab/ndt7-js/issues/4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/39)

Pass http parameters prefixed with "client_" to generated urls

---

clientgeo/appengine.go
clientgeo/appengine_test.go
clientgeo/locator.go
clientgeo/locator_test.go
handler/handler.go
handler/handler_test.go
handler/monitoring_test.go
locate.go
locatetest/locatetest.go

This change moves the "findLocation" logic from the http handler to a new `clientgeo` package. We want to add additional methods of looking up the client location. This is the first step to making an general interface for that operation.
This change better distinguishes the ServiceUnavailable and InternalServiceError cases. Unit tests are updated accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/42)

Add clientgeo package for appengine location

---

clientgeo/user.go
clientgeo/user_test.go
locate.go

This change uses the Locator interface to add support for user-provided location hints using `country=` or `region=` http parameters. This Locator is registered first, so takes precedence over both the AppEngine and Maxmind Locators.
Regardless of a user's actual location when they make the request, the user-provided location parameters are considered first. For example, this would allow a user in US-NY to get access tokens and run a measurement to servers in DE.
The set of country and region codes recognized are the same as those defined in https://github.com/m-lab/locate/tree/master/static.
Example usage would be:
* https://locate.measurementlab.net/v2/nearest/ndt/ndt7?country=DE  (Germany)
* https://locate.measurementlab.net/v2/nearest/ndt/ndt7?region=DE-BE (Berlin specifically)
Part …

Add support for user-provided location hints

---

clientgeo/appengine.go
clientgeo/appengine_test.go
clientgeo/locator.go
clientgeo/maxmind.go
clientgeo/maxmind_test.go
clientgeo/user.go
clientgeo/user_test.go
locate.go

This change replaces all instances of "X-Locate-Client*" headers with constant names to fix a bug where the maxmind headers were not returned correctly.
This bug was caused by the inline definition of `http.Headers` with non-canonical header key names, https://github.com/m-lab/locate/blob/e2fd31484cdb6603f4209cfe294b23f965d4c069/clientgeo/maxmind.go#L78-L81
combined with the header copy loop using `http.Header.Get` and `http.Header.Set` methods, which normalize key names strictly using `textproto.CanonicalMIMEHeaderKey`. https://github.com/m-lab/locate/blob/e2fd31484cdb6603f4209cfe294b23f965d4c069/handler/handler.go#L120-L122
So, the copy loop used canonical names while the underlying map had non-canonical keys. As a result, they were unnameable.
This bug does not effect the maxmind …

Use constant names for X-Locate-Client* headers

---

USAGE.md

This PR adds some detail to USAGE.md outlining how Appengine locates a client, and how the country and region parameters may be used to select an alternate location.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/49)

Add location details to Usage.md

---

api/v2/api.go
cloudbuild/cloudbuild.yaml
cmd/monitoring-token/monitoring-token.go
cmd/monitoring-token/monitoring-token_test.go
cmd/monitoring-token/testdata/check_env.sh
handler/monitoring.go

This PR has two components:
* adds a new flag `-monitoring-url-only`, which will cause the monitoring-token command to set the environment variable (named by `-env-name`) with a value of the authenticated /v2/monitoring URL rather than a service URL. The impetus for this is the wehe-cmdline client, which accepts a `-m` flag which sets the URL at which to query the M-Lab locate service.
* Currently, the locate service returns different data for "normal" locate queries and "monitoring" queries. This means that clients cannot consistently parse the results of both using the same code. This PR adds a new `results` key to the monitoring response which matches the format of a normal locate query.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

New monitoring-token flag + adds `results` key to monitoring responses

---

static/configs.go

This PR maps `wehe/replay` to an actual live wehe status from mlab-ns. It is intended to resolve #47.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/52)

Maps wehe/replay to mlab-ns/wehe, not ndt7

---

secrets/load.go
secrets/load_test.go

This PR adds a new package named `secrets`. It serves the same general purpose as the current `decrypt` package, but uses a different backing mechanism. Instead of using the GCP Key Management Service (KMS) (like `decrypt`), this new package uses the GCP Secret Manager (SM).
The primary motivation for moving to the SM is that, currently, the signer and verify keys for the Locate Service are stored in this public repository in encrypted form. It is probably safe, but perhaps better to remove them altogether in any form. Moving to the SM allows us to remove the keys 100% from this repo. This new module will allow the Locate Service to fetch the keys directly from the SM at runtime.
Another advantage of using the SM over KMS, is that the SM natively supports secret versions, which will allow …

Adds new package named secrets

---

.travis.yml
cmd/heartbeat/README.md
cmd/heartbeat/main.go
cmd/heartbeat/main_test.go
connection/connection.go
connection/connection_test.go
connection/testdata/fakeserver.go
go.mod
go.sum
handler/heartbeat.go
static/configs.go

This change adds the heartbeat service.
It uses the connection package to establish a persistent connection with the Locate and send heartbeat messages at periodic intervals. If the connection is dropped, it automatically tries to reconnect using an exponential backoff implementation for retries. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/64)

Add heartbeat service connection

---

cloudbuild/app.yaml.template

This change adds an explicit network name for the Locate app.yaml to resolve deployment failures in mlab-ns/production.
As well, since our primary projects (sandbox, staging, production) used very different default network configurations, this change depends on a new purpose-created `locate` VPC network in each project. For example:
```
gcloud --project mlab-sandbox compute networks create locate --subnet-mode=auto --bgp-routing-mode=regional
gcloud --project mlab-sandbox compute firewall-rules create locate-allow-internal --network locate --allow tcp,udp,icmp --source-ranges 0.0.0.0/0
gcloud --project mlab-sandbox compute firewall-rules create locate-allow-ssh --network locate --allow tcp:22,tcp:3389,icmp
```
These changes were necessary b/c during a routine deployment the mlab-ns …

Explicit network name in app.yaml

---

cmd/heartbeat/Dockerfile.heartbeat

This PR adds the `@latest` to the `Dockerfile.heartbeat` path, which was removed when the prometheus flag was added.
Error [log](https://hub.docker.com/repository/registry-1.docker.io/measurementlab/heartbeat/builds/6985fa4c-4012-4689-b3e9-564da5772c46):
```
#13 0.406 fatal: not a git repository (or any of the parent directories): .git
#13 0.412 go: 'go install' requires a version when current directory is not in a module
#13 0.412 Try 'go install github.com/m-lab/locate/cmd/heartbeat@latest' to install the latest version
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/81)

Add @latest to Dockerfile.heartbeat

---

static/configs.go

neubot/dash currently still uses mlab-ns, but is migrating to locate. @bassosimone expressed a preference toward wrapping dash's endpoint with the access controller directly (rather than using the envelope sidecar mechanism) similarly to what ndt-server does.
DASH's test endpoints  (`/dash/download/<number_of_bytes>`) won't work unless the client has called `/negotiate/dash` first and has received a valid session ID, so securing `/negotiate/dash` makes sure that tests cannot be run without a valid access token.
This PR changes the static config for `neubot/dash` to provide the correct URL (`https://<server>/negotiate/dash?access_token=...`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Fix dash URL in the static configuration

---

go.mod
go.sum
handler/handler.go

This PR changes the token generation so that the `jwt.Claims.ID` field (which becomes `jti` in JWT) is populated with a new UUID each time.
This makes each generated token unique, which in turn makes them viable as "session IDs" for measurements that make multiple calls across different endpoints/servers, and potentially allows us to check if tokens are being misused.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/84)

Make generated tokens unique

---

handler/handler.go
handler/handler_test.go
handler/heartbeat_test.go
handler/monitoring_test.go
handler/prometheus.go
handler/prometheus_test.go
heartbeat/heartbeat.go
heartbeat/location.go
locate.go
locatetest/locatetest.go
metrics/metrics.go
metrics/metrics_test.go
openapi.yaml
static/configs.go

This PR adds a handler for /v2/platform/prometheus requests.
The handler is triggered by a [Cloud Scheduler](https://pantheon.corp.google.com/cloudscheduler?project=mlab-sandbox) job that runs every minute. The job does not interfere with the App Engine cron job configuration defined in [`mlab-ns`](https://github.com/m-lab/mlab-ns/blob/main/cron.yaml). It will also continue to work when the Locate moves to GKE.
The openapi configuration enforces the usage of an API Key to make requests..
The handler queries Prometheus for GMX and end-to-end metrics. It creates a map of label values (e.g., service hostname or machine name) to bool values (e.g., false if the script was unsuccessful or the machine is in maintenance, true otherwise) and passes the information to the …

Add handler for Prometheus cronjob

---

cloudbuild/cloudbuild.yaml
cmd/heartbeat/health/kubernetes-client.go
cmd/heartbeat/health/kubernetes-client_test.go

The current error status contains a URL like the following:
```
Get "https://api-platform-cluster.mlab-sandbox.measurementlab.net:6443/api/v1/namespaces/default/pods/ndt-virtual-7qzzs": context deadline exceeded
Get "https://api-platform-cluster.mlab-sandbox.measurementlab.net:6443/api/v1/namespaces/default/pods/ndt-virtual-7qzzs": http2: client connection lost
Get "https://api-platform-cluster.mlab-sandbox.measurementlab.net:6443/api/v1/namespaces/default/pods/ndt-virtual-d6zzj": context deadline exceeded
Get "https://api-platform-cluster.mlab-sandbox.measurementlab.net:6443/api/v1/namespaces/default/pods/ndt-virtual-d6zzj": http2: client connection lost
```
This PR makes the error for the metric generic and logs the more specific one.
- - -
This change is [<img …

Make Kubernetes metric error generic

---

metrics/metrics.go

This PR removes the predefined buckets from the Kubernetes duration histogram so that the results fall under their natural buckets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/89)

Remove buckets from histogram metric

---

handler/heartbeat.go
handler/heartbeat_test.go
metrics/metrics.go
metrics/metrics_test.go

This PR adds a new "experiment" label to the heartbeat connections gauge. This will allow filtering of the number of expected connections on Grafana dashboards based on the experiment.
Example: https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service?orgId=1&refresh=5s&viewPanel=10
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/90)

Add 'experiment' label to heartbeat connections gauge

---

cmd/heartbeat/Dockerfile.heartbeat

Use the local path in `go install`.
This populates the `git_short_commit` metric.
https://prometheus-platform-cluster.mlab-sandbox.measurementlab.net/graph?g0.expr=git_short_commit%7Bcontainer%3D%22heartbeat%22%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=2h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/93)

Install local path in Dockerfile.heartbeat

---

handler/handler.go
handler/handler_test.go
heartbeat/location.go
heartbeat/location_test.go
locatetest/locatetest.go

This PR adds in-country biasing for the Locate V2.
App Engine returns a valid country code for over 99% of requests, so this implementation uses its `X-AppEngine-Country` request header to double the distance for instances in a different country.
If the country in the request is empty or unknown ("ZZ"), or if the instance is in the same country as the client, there is no change.
*Note: this is not urgent. It can wait until after the holidays.*
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/94)

Add in-country biasing for Locate V2

---

locate.go

Changes tested with these URLs:
-  https://locate-dot-mlab-sandbox.appspot.com/v2/nearest/demo1/ndtm
- https://locate-dot-mlab-sandbox.appspot.com/v2/nearest/ndt/ndt7
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/96)

Use Locate V2 to serve /v2/nearest requests in sandbox

---

handler/handler.go

Results with the `locate_version` parameter appended at the end can be seen in sandbox (e.g., https://locate-dot-mlab-sandbox.appspot.com/v2/nearest/ndt/ndt7) 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/97)

Add locate_version parameter to output urls

---

heartbeat/heartbeat.go
heartbeat/heartbeat_test.go
heartbeat/location.go
metrics/metrics.go
metrics/metrics_test.go

This PR removes the `locate_health_status` and `prometheus_health_status` metrics and combines them into one `locate_health_status` metric that uses the experiment as the label.
It also removes a flaky test (`TestStopImport`).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/100)

Modify health count metric

---

heartbeat/location.go

This PR temporarily removes the in-country biasing since it is superseding user-provided parameters. 
It will be added back as a complement to the user-provided parameters after the rollout analyses are complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/104)

Remove in-country biasing

---

handler/heartbeat_test.go

This PR removes a flaky test that waits a certain amount of time to confirm that a goroutine has exited. It will be replaced by a better test soon.
Note: there are no remaining similar tests in this repo 👼.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/105)

Remove flaky test

---

static/configs.go

We are going to continue experimenting with virtual-only metros, adding these two metros Sao Paulo (gru) and Tokyo (hnd) to the ongoing experiment in bom. Part of this will be treating the virtual sites in these metros like phyiscal site, 100% probability.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/107)

Removes reduced probability for sites hnd06 and gru05

---

heartbeat/heartbeat.go

There is locking for writing, but not for reading health information. The library has a special [`RLock`](https://pkg.go.dev/sync#RWMutex.RLock) to use for reading.
This PR fixes this error stack found in the logs:
```
DEFAULT 2023-01-19T14:45:31Z fatal error: concurrent map iteration and map write
DEFAULT 2023-01-19T14:45:31Z
DEFAULT 2023-01-19T14:45:31Z goroutine 3477 [running]:
DEFAULT 2023-01-19T14:45:31Z runtime.throw({0xd13b91?, 0xe6?})
DEFAULT 2023-01-19T14:45:31Z /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc000281720 sp=0xc0002816f0 pc=0x439ed1
DEFAULT 2023-01-19T14:45:31Z runtime.mapiternext(0xbcb4e0?)
DEFAULT 2023-01-19T14:45:31Z /usr/local/go/src/runtime/map.go:871 +0x4eb fp=0xc000281790 sp=0xc000281720 pc=0x411bab
DEFAULT 2023-01-19T14:45:31Z …
```

Add lock for concurrent reading of health information

---

cloudbuild/app.yaml.template

The target CPU is currently set to the default (0.5), which is causing App Engine to constantly upscale and downscale instances. This PR decreases the target CPU to 0.3, so there are more instances available and upscaling is needed less frequently.
The PR also increases the cool down period to 10 minutes to avoid readiness errors when a new instance is created.
https://prometheus.mlab-oti.measurementlab.net/graph?g0.expr=locate_requests_total%7Binstance%3D%22aef-locate-20230120t215558-tm9d%22%7D&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h38m34s975ms&g0.end_input=2023-01-26%2000%3A06%3A04&g0.moment_input=2023-01-26%2000%3A06%3A04
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Adjust cool down period and target CPU

---

cloudbuild/app.yaml.template
handler/handler.go
handler/heartbeat.go
heartbeat/heartbeat.go
metrics/metrics.go
metrics/metrics_test.go

This PR reverts the target CPU utilization to the default value it was using [before](https://github.com/m-lab/locate/pull/109/files) (i.e., [0.5](https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=go#automatic_scaling)) and it adds new metrics and labels.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/111)

Revert target CPU and add more metrics

---

handler/handler.go

This change enables the site filter query option. With this change clients can specify a set of sites returned in the results.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/99)

Allow site filter query parameters

---

static/configs.go

Double probabilities for virtual sites and add 10% probability for physical sites in bom, hnd, and gru.
Related to https://github.com/m-lab/ops-tracker/issues/1665.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/112)

Update site probabilities after cloud 1st experiments

---

heartbeat/location.go
heartbeat/location_test.go
metrics/metrics.go
metrics/metrics_test.go

This PR adds a new metric to track the ranked distance of the selected servers with respect to the client (e.g., 1st closest, 2nd closest).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/121)

Add histogram to track ranked distance of selected servers

---

cloudbuild/cloudbuild.yaml

This PR re-enables the `--promote` flag in mlab-ns now that we've implemented https://github.com/m-lab/locate/pull/119 and https://github.com/m-lab/locate/pull/118 to fix and have more visibility into promotion outages such as https://github.com/m-lab/locate/issues/114.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/122)

Enable the --promote flag in mlab-ns

---

cloudbuild/cloudbuild.yaml
connection/connection.go
connection/connection_test.go
static/configs.go

This PR removes the 10 reconnections per hour cap. It also reduces the reconnection backoff maximum interval to 5 minutes.
When a new version is promoted/created, the heartbeat instances briefly disconnect from the old version and reconnect to the new one. This can sometimes take a surprisingly long time if an instance hits the maximum number of reconnections attempts (10), at which point it has to wait a whole hour to reconnect, or if the retry backoff increases significantly.
This scenario can be reproduced in sandbox. That said, the problem is much less likely to happen since the introduction of the App Engine [custom request handlers](https://github.com/m-lab/locate/pull/118). 
This is part of the remediation for https://github.com/m-lab/locate/issues/114.
This change is [<img …

Remove cap for number of reconnections per hour

---

handler/heartbeat.go
handler/heartbeat_test.go
heartbeat/heartbeat.go

This PR adds logging and closes the heartbeat connection whenever there is an error writing to Memorystore.
It also adds a `conn` interface for the heartbeat handler to take in.
Related to https://github.com/m-lab/locate/issues/114.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/123)

Close heartbeat connection on write error

---

metrics/metrics.go

This PR changes the max for the `locate_server_distance_ranking` to 20. Even though we have hundreds of servers, practically, the ranked distance of the selected servers will almost always be less than 20.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/124)

Change server ranking metric max to 20

---

handler/handler.go
handler/handler_test.go
heartbeat/location.go
heartbeat/location_test.go
locatetest/locatetest.go
metrics/metrics.go
metrics/metrics_test.go

This PR adds a new `metro_rank` parameter to the output URLs. Specifically, it adds a `Ranks` field to the output of the `LocatorV2.Nearest()` function containing a mapping of machine hostnames to their metro ranking (based on distance from the client).
It also adds the metro ranking to a `locate_metro_distance_ranking` histogram metric.
The URL parameter can be seen [here](https://locate-dot-mlab-sandbox.appspot.com/v2/nearest/ndt/ndt7) and the metric [here](https://prometheus.mlab-sandbox.measurementlab.net/graph?g0.expr=locate_metro_distance_ranking_bucket&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=12h).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/126)

Add metro ranking

---

static/configs.go

We are going to keep these two physical sites. Send them full traffic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/128)

Removes hnd02 and hnd04 from SiteProbability map

---

cloudbuild/app.yaml.template

This PR sets the minimum number of App Engine instances to 15 (the default is 2).
The number 15 was picked because the minimum number of instances that App Engine scales down to in mlab-ns seeems to be ~13, so 15 would be a safe, round minimum which would at most only result in ~2 extra instances.
When no minimum is set, the instances gradually come up as a new version is deployed. This causes the Load Balancer to throw 502 errors with the reason `failed_to_pick_backend`. 
These errors can be seen on App Engine's dashboard right after a new version is deployed.
- Last deployment to mlab-ns:
- Issue reproduced in staging:
They can also be seen in the logs ([mlab-ns](https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22http_load_balancer%22%0AhttpRequest.status%3D502;timeRang …

Add minimum number of instances

---

heartbeat/location_test.go
static/configs.go

This change increases all virtual sizes from 0.2 to 0.3.
As well, this change increases iad07 and chs01 (both cloud locations in US) to 1.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/130)

Update site probabilities

---

static/configs.go

This change increases the site selection probability for three cloud sites to aid with the spread analysis around LGA.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/131)

Increase north east virtual sites to 1.0

---

static/configs.go

This change reduces the probability of all LGA sites to 0.5. This temporary spray experiment is in service of sending more clients that would ordinarily be directed to LGA to other nearby metro areas and Cloud sites, specifically: IAD, YUL, YYZ, and possibly CMH or CHS).
This configuration update is necessary to limit the impact to only LGA clients and to use an already available mechanism in the Locate service.
This setting should be reverted in 1 week.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/132)

Add lga sites for larger spray experiment

---

static/configs.go

This change reverts the lower probability for LGA sites and concludes the spray experiment between LGA & IAD.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/133)

Revert LGA spread experiment

---

static/configs.go

Following the LGA trial (https://github.com/m-lab/locate/pull/132 https://github.com/m-lab/locate/pull/133) this change updates sites at the ATL metro to 0.5 to distribute more clients to CHS in Google Cloud. This is a limited trial that will run for only one week.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/134)

Reduce ATL metro probability to .5 (for one week)

---

static/configs.go

This change reverts the temporary reduced site probabilities around ATL https://github.com/m-lab/locate/pull/134 - after collecting data for one week, we should have sufficient data for a similar spray analysis between ATL and CHS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/135)

Remove ATL adjustments

---

static/configs.go

This change updates site probabilities to bias towards GCP regions that are "remote but maybe close enough". This change follows trial with LGA/IAD and ATL/CHS and applies similar configurations for all remaining regions summarized below:
Site | GCP | Traffic Migration | 
-- | -- | -- |
ATL | South Carolina | ATL->South Carolina | 
NUQ | Los Angeles | NUQ->Los Angeles | 
ARN | Finland | ARN->Finland | 
YVR | Oregon | YVR->Oregon |
MIA | South Carolina | MIA->South Carolina |
DEN | Salt Lake City | DEN->Salt Lake City |
EZE | Santiago | EZE->Santiago |
MRS | Turin | MRS->Turin |
PRG | Frankfurt | PRG->Frankfurt |
GIG  | Sao Paulo | GIG -> Sao Paulo |
Note:
* we are enabling the ATL probability changes to collect more data.
* site probabilities are lower than previous changes (0.5 for lga, …

Add static configs for all remote GCP regions

---

static/configs.go

This change reverts the physical site probability changes that were part of the trail started in https://github.com/m-lab/locate/pull/136
The cloud sites that were increased to 1.0 remain at 1.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/137)

Remove trial adjustments to physical sites

---

static/configs.go

Since physical site dfw05 was retired, the remaining dfw sites have become overloaded, especially by periodic spike traffic. Giving the virtual dfw site full probability will hopefully help alleviate some of the traffic issues to the remaining physical sites. We will also add additional VMs to dfw09.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/140)

Increases virtual site dfw09 probability to 1.0

---

handler/handler.go
handler/handler_test.go

This PR adds functionality to add the `early_exit` client flag to the server URLs with a probability of 1%.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/139)

Implement early_exit probability

---

cmd/heartbeat/main.go
cmd/heartbeat/main_test.go

This PR adds functionality to the heartbeat to handle SIGTERM signals from the OS.
The changes were tested locally by getting the processing id and sending a `kill -15 $pid` signal.
```
$ ./heartbeat     -heartbeat-url=ws://locate-dot-mlab-sandbox.appspot.com/v2/platform/heartbeat?key=${key}     -registration-url=https://siteinfo.mlab-sandbox.measurementlab.net/v2/sites/registration.json     -hostname=ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org     -services=ndt/ndt7=ws:///ndt/v7/download,ws:///ndt/v7/upload     -services=ndt/ndt7=wss:///ndt/v7/download,wss:///ndt/v7/upload
2023/06/29 19:18:58 successfully established a connection with ws://locate-dot-mlab-sandbox.appspot.com/v2/platform/heartbeat?key=${key}
3976599
Received signal:  terminated
```
Related to …

Add a SIGTERM handler for the heartbeat

---

cmd/heartbeat/health/checker.go
cmd/heartbeat/health/checker_test.go
cmd/heartbeat/health/endpoint-check.go
cmd/heartbeat/health/endpoint-check_test.go
cmd/heartbeat/health/healthtest/healthtest.go
cmd/heartbeat/main.go
static/configs.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/145)

Add timeout for /health endpoint checks

---

cmd/heartbeat/main.go
metrics/metrics.go
metrics/metrics_test.go

This PR adds a new metric to keep track of how long it takes for the heartbeat to calculate the local health score and send it to the Locate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/147)

Add histogram for health transmission duration

---

metrics/metrics.go

This PR changes the maximum number of buckets for the health transmission histogram since the Memorystore timeout is 30 seconds (2 * 16  = 31 steps from 0 to 30), so the distinction for any latency after that is not relevant (e.g., 32 seconds has the same effect as 40).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/150)

Change number of buckets for health transmission duration metric

---

memorystore/client.go
memorystore/client_test.go
metrics/metrics.go
metrics/metrics_test.go

This PR adds a new metric to keep track of how long it takes for the Locate to issue requests to Memorystore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/152)

Locate: Add histogram for Memorystore request duration

---

cloudbuild/app.yaml.mlab-ns.template

This PR reduces the minimum number of VMs in the mlab-ns project to 12 to safely stay under the CPU quota (120) during deployments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/156)

Reduce minimum number of VMs to 12

---

handler/handler.go

This PR increases the probability of early-exit tests from 1% to 10%. 
The set of checks performed are described under [this](https://github.com/m-lab/ndt-server/issues/395#issuecomment-1726338260) launch issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/160)

Locate: Increase early-exit probability to 10%

---

handler/handler.go

This PR increases the probability of early-exit tests from 10% to 30%.
The set of checks performed are described under [this](https://github.com/m-lab/ndt-server/issues/395#issuecomment-1736065583) launch issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/161)

Locate: Increase early-exit probability to 30%

---

handler/handler.go

This PR extends the rate limit period for the 3-hour client to 15 minutes past the hour. There seems to be a retry period that extends a little bit over 10 minutes.
[Prometheus](https://prometheus.mlab-oti.measurementlab.net/graph?g0.expr=sum%20by%20(status)%20(rate(locate_requests_total%7Btype%3D%22nearest%22%7D%5B2m%5D))&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=14m6s177ms&g0.end_input=2023-10-02%2022%3A16%3A01&g0.moment_input=2023-10-02%2022%3A16%3A01) shows a spike in the "OK" requests right after the 10 minute mark.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/163)

Extend rate limit period to 15 minutes

---

handler/handler.go

This PR increases the probability of early-exit tests from 30% to 50%.
The set of checks performed are described under the [launch issue](https://github.com/m-lab/ndt-server/issues/395#issuecomment-1745617873).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/164)

Locate: Increase early-exit probability to 50%

---

handler/handler.go
handler/handler_test.go

This PR adds a new result "index" parameter to the set of returned URLs to have visibility into potential failovers on the client side.
Sample result from https://locate-dot-mlab-sandbox.appspot.com/v2/nearest/ndt/ndt7: "ws://ndt-mlab2-lga1t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjItbGdhMXQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjk5NDU3NTY5LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiJmMzk2ZDYyNy1lMDNlLTQ4YjMtOGM0Mi1mNjAzOWNhNGVjMDAiLCJzdWIiOiJuZHQifQ.S2QjfZdFt-JJCZcKtzfvEXF9IYUJ9QmayfzgOWJAb4PSRw0tCU8fkR_LdfzGRcdeHrcy4f0fBOayqsLvpQKKBw\u0026**index=0** \u0026locate_version=v2\u0026metro_rank=0"
Related to https://github.com/m-lab/ops-tracker/issues/1859
- - -
This change is [<img …

Add result index parameter to URLs

---

handler/handler.go

This PR increases the probability of early-exit tests from 50% to 90%.
The set of checks performed are described under the launch issue ([1](https://github.com/m-lab/ndt-server/issues/395#issuecomment-1806005414), [2](https://github.com/m-lab/ndt-server/issues/395#issuecomment-1806027426)).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/167)

Increase early exit probability to 90%

---

heartbeat/location.go
heartbeat/location_test.go

I tested using this small Go program:
```
package main
import (
"fmt"
"time"
"github.com/m-lab/go/mathx"
)
func main() {
r := mathx.NewRandom(time.Now().UnixNano())
for rate := 1; rate < 7; rate++ {
keys := make(map[int]int)
for i := 0; i < 10000000; i++ {
index := r.GetExpDistributedInt(float64(rate)) % 5
keys[index]++
}
fmt.Printf("Rate %d: %v\n", rate, keys)
}
}
```
... which yields something like:
```
$ go run main.go 
Rate 1: map[0:4004697 1:3860959 2:1419117 3:522604 4:192623]
Rate 2: map[0:6323166 1:3180105 2:430647 3:58221 4:7861]
Rate 3: map[0:7769307 1:2119101 2:106222 3:5116 4:254]
Rate 4: map[0:8647798 1:1327257 2:24507 3:427 4:11]
Rate 5: map[0:9179218 1:815219 2:5525 3:38]
Rate 6: map[0:9501968 1:496809 2:1219 3:4]
```
A rate of 6 appears to return an index of 0 ~95% of the …

Passes a rate of 6 to the exponentially distributed selection function

---

DEVELOPMENT.md
docker-compose.yaml
locate.go

This change removes an obsolete flag from `docker-compose.yaml` and updates locate.go initialization to allow `-key-source=local` for local development. Finally, this change adds a new `DEVELOPMENT.md` with hints for setting up locate, redis, heartbeats, pseudo services, and querying using `redis-cli`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/175)

fix: allow local development (with new documentation)

---

clientgeo/user.go
handler/handler.go
heartbeat/location.go
heartbeat/location_test.go

The default behavior when the `country` parameter is provided is to override client location with the geographical center of the requested country, then apply the normal algorithm to find the nearest servers. 
This PR adds the `strict` parameter which, when used in conjunction with `country`, limits the results to servers in the requested country and _does not_ override the client location.
Examples: 
- `country=GB` - returns servers that are the closest to GB's geographical center (even if they happen to be outside GB)
- `country=GB&strict=true` - returns servers that are closest to the user's location, but strictly in GB
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/177 …

Add "strict" querystring parameter

---

cloudbuild/cloudbuild.yaml
openapi.yaml

This change labels the deployment environment with the sandbox or staging project name or simply "Production" for M-Lab's production environment.
This change will help us distinguish between the different deployments internally, and signal to third parties that the "Production" API is for production use.
Without:
With:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/178)

Label the Locate API name with deployment environment

---

handler/handler_test.go

This change removes a fake locator previously used in tests and now obsolete. Should have been removed by https://github.com/m-lab/locate/pull/172
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/186)

Remove obsolete test logic

---

cmd/heartbeat/registration/registration.go
cmd/heartbeat/registration/registration_test.go
cmd/heartbeat/registration/testdata/registration.json

Hostnames registered via the [autojoin](https://github.com/m-lab/autojoin) service always include a service prefix. This PR makes heartbeat check for both "w/ service" and "w/o service" keys in registration.json so that it will be able to work with autojoin hostnames.
e.g. registration.json:
```
{
"ndt-lga46450-8e9ad576.mlab.sandbox.measurement-lab.org": {
[...]
}
}
```
`$ ./heartbeat -registration-url=registration.json -hostname ndt-lga46450-8e9ad576.mlab.sandbox.measurement-lab.org`
This would previously fail because heartbeat checks for `lga46450...` stripping the `ndt-` prefix in registration.json. 
In the (unlikely) case that both w/service and w/o service keys are present in registration.json, the one without a service prefix takes precedence.
- - -
This change is [<img …

Support autojoin hostnames in registration.json

---

cmd/heartbeat/main.go
cmd/heartbeat/main_test.go

Previously, the file /metadata/loadbalanced only existed on MIG instances. We recently decided that the file should exist on every machine with either a "true" or "false" value. Locate was only checking for the file's existence to determine if the machine was loadbalanced or not, but since this is no longer a valid signal, this commit causes heartbeat to read the value of the file, and only treat the machine as loadbalanced if the value is "true".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/191)

 Reads value of var lbPath (/metadata/loadbalanced)

---

handler/handler.go
handler/handler_test.go
static/configs.go

This PR adds functionality to specify a set of common service parameters supported by the Locate. 
For each parameter in the client request (e.g., early_exit), the Locate specifies a probability (e.g., 0.9) with which the parameter will be added to the server URL.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/192)

Add service parameters map

---

handler/handler_test.go
static/configs.go

This PR adds the `max_elapsed_time` client parameter to the Locate's service parameters map to be able to pass it to the server in the URL.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/193)

Add max_elapsed_time to service parameters

---

locate.go
secrets/load.go
secrets/load_local.go
secrets/load_local_test.go
secrets/load_test.go

This change is a cleanup to the `secrets.NewConfig` interface to encapsulate the `SecretClient` to simplify the interface of all `Load*` operations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/194)

Encapsulate SecretClient in NewConfig

---

cmd/monitoring-token/monitoring-token.go
handler/monitoring.go

This change is part of support for end to end monitoring of the autonode deployments in sandbox and staging (and production). This change preserves request parameters to the Locate API when generating monitoring access tokens. This allows us to use the `early_exit=250` parameter on tests for monitoring, reducing overall resource consumption.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/198)

Pass additional parameters to and through monitoring requests

---

handler/prometheus.go

There are errors (i.e., response code = 500) in the requests from the [Cloud Scheduler job](https://console.cloud.google.com/logs/query;query=resource.type%3D%22cloud_scheduler_job%22%20AND%20resource.labels.job_id%3D%22prometheus%22%20AND%20resource.labels.location%3D%22us-central1%22;cursorTimestamp=2024-10-31T16:32:02.375967863Z;startTime=2024-10-31T16:11:32.385Z;endTime=2024-10-31T18:11:32.385774Z?project=mlab-ns) to update the Locate's internal Prometheus state. However, because we don't have logging for request errors, we don't know what's causing them. This PR adds logging for such cases.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/199)

Add logging for the Prometheus health handler

---

handler/prometheus.go
handler/prometheus_test.go

This PR fixes the machine hostname used to query Prometheus for a single machine. Before, it was only passing in the "mlabN" part. Now, it's passing in the full name, which is needed to filter the metrics ([example](https://prometheus.mlab-oti.measurementlab.net/graph?g0.expr=gmx_machine_maintenance%7Bmachine%3D%22mlab1-atl04.mlab-oti.measurement-lab.org%22%7D&g0.tab=1&g0.display_mode=lines&g0.show_exemplars=0&g0.range_input=1h)).
Note: I'm not sure what is happening with Coveralls. That file was not modified.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/204)

Use correct machine hostname for Prometheus query

---

handler/heartbeat.go
handler/heartbeat_test.go

This PR fixes the parameter for the single instance Prometheus update to be the Hostname.
This fixes the error: `Error parsing hostname mlab2`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/205)

Pass in hostname to Prometheus single instance update

---

handler/prometheus.go
handler/prometheus_test.go

Apologies, I thought this was fully fixed but I see it's not. Prometheus label values take surrounding quotes (e.g., script_success{machine="mlab1-atl04.mlab-oti.measurement-lab.org"}. This PR adds them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/207)

Add surrounding quotes to machine label name

---

USAGE.md

This change adds documentation to USAGE.md for the new request parameters `org=` and `site=`. These are helpful for creating host portals for autonode site hosts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/206)

Add USAGE.md for new request parameters

---

siteinfo/siteinfo.go
siteinfo/siteinfo_test.go

The siteinfo package will generate various formats, which will all be variations of heartbeat registration information. It is intended to at least partially handle what the siteinfo repository does not provide. Today, siteinfo has no information about autojoin machines, and in the not-distant future siteinfo will likely no longer track VMs either. On the other hand, Locate knows about _all_ machines on the platform.
As a start, this new package only implements a singe "Machines" format, which is nothing more than a dump of all v2.HeartbeatMessages that Locate knows about. Eventually it can support formats like "Geo", "Sites", etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Adds new siteinfo package

---

handler/handler.go
handler/handler_test.go
heartbeat/heartbeattest/heartbeattest.go
locate.go
openapi.yaml

A new path specification of /v2/siteinfo/registrations was added. Requests to this endpoint will be handled by the siteinfo package. The endpoint supports 3 query parameters:
* format - defines the format of the returned JSON
* org - limits results to only records for the given organization (e.g., mlab, rnp, etc.)
* exp - limits results to only records for the given experiment (e.g., ndt, msak, etc.)
It seems to working as intended: https://mlab-sandbox.appspot.com/v2/siteinfo/registrations
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/209)

Add new handler for the recently added siteinfo package

---

cloudbuild/app.yaml.mlab-ns.template
cloudbuild/app.yaml.template
cloudbuild/cloudbuild.yaml
go.mod
go.sum
handler/handler.go
handler/handler_test.go
handler/heartbeat_test.go
handler/monitoring_test.go
limits/ratelimiter.go
limits/ratelimiter_bench_test.go
limits/ratelimiter_test.go
locate.go

Implements a rate limiter backed by Redis' sorted sets (ZSETs).
```
// It maintains a sliding window of events for each IP+UA combination, where:
//   - Each event is stored in a ZSET with the timestamp as score
//   - Old events (outside the window) are automatically removed
//   - Keys automatically expire after the configured interval
//
// The limiter considers a request to be rate-limited if the number of events
// in the current window exceeds MaxEvents.
```
Initially we are only going to log which IP+UA are being rate limited and increase a Prometheus counter. Once we confirm that the limiter is WAI, we can start actually rejecting requests.
I used a separate Redis instance because:
- The memorystore package appears to assume its Redis instance won't be used for anything else and …

Implement rate limiting based on IP+UA

---

handler/handler.go

When I changed the handler to not actually block I kept a reference to `result` that's nil at that point.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/212)

Fix nil pointer in Nearest handler

---

handler/handler.go
handler/handler_test.go
limits/ratelimiter.go
limits/ratelimiter_bench_test.go
limits/ratelimiter_test.go
locate.go
metrics/metrics.go

This allows to have different per-IP and per-IP+UA intervals and thresholds. If the IP address made more than X requests in Y time, the IP+UA key is ignored.
Adds the `-rate-limit-ip-interval` and `-rate-limit-ip-max` to configure this new rate limiting rule.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/219)

Update rate limiter to have different configurable limits for IP-only and IP+UA

---

cloudbuild/app.yaml.mlab-ns.template
cloudbuild/app.yaml.template
cloudbuild/cloudbuild.yaml
handler/handler.go
handler/handler_test.go
handler/heartbeat_test.go
handler/monitoring_test.go
locate.go
static/configs.go

This flag allows to specify a list of clients that we know support early exit and for which early exit should always be added to the generated URLs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/223)

Add -early-exit-clients command-line flag

---

go.mod
go.sum
handler/handler.go
heartbeat/location_test.go
locate.go
siteinfo/siteinfo.go
siteinfo/siteinfo_test.go

This new format will be used by the status map on the M-Lab website, making the map realtime instead of just whatever siteinfo lists. It will also include host-managed sites, which the siteinfo data lacks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/224)

Adds a new "geo" format the /v2/siteinfo/registrations endpoint

---

siteinfo/siteinfo.go
siteinfo/siteinfo_test.go

There was a case in staging where Locate was returning this for a host:
"neubot-mlab4-syd04.mlab-staging.measurement-lab.org": {
"Health": null,
"Registration": null,
"Prometheus": {
"Health": false
}
},
... this was causing a panic in Locate. This commit avoids this, and adds a new unit test to be sure it working as intended. Interestingly, syd04 was retired in 2023, so it's not clear why Locate is hanging on to a record for this machine.
I also renamed `v` in the for loop to `h` to avoid being confusion with the `v` function parameter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/227)

Avoids a nil pointer dereference error in Geo()
