README.md
api/v2/api.go

FYI: now this repo is tracked in the big dev-tracker table too!
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/9)

More badges and a typo fix

---

cloudbuild/cloudbuild.yaml

Add missing project for deployment to mlab-ns project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/12)

Include mlab-ns in allowed projects pattern

---

openapi.yaml

This change makes the HEAD be consistent with the config deployed in production currently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/23)

Disable apikey security temporarily

---

USAGE.md

This change adds basic usage information and examples of querying the `/v2/nearest` resource in the Locate API.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/25)

Add initial USAGE.md

---

USAGE.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/50)

Fix reference links

---

cloudbuild/app-platform.yaml.mlab-ns
cloudbuild/app-platform.yaml.mlab-sandbox
cloudbuild/app-platform.yaml.mlab-staging
cloudbuild/app.yaml.mlab-ns
cloudbuild/app.yaml.mlab-sandbox
cloudbuild/app.yaml.mlab-staging

I believe this should resolve the following issue:
https://github.com/m-lab/dev-tracker/issues/675
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/53)

Uses automatic scaling in favor of manual scaling

---

cmd/monitoring-token/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/60)

Fix funny typo

---

go.mod
go.sum
handler/handler.go
handler/handler_test.go
handler/heartbeat.go
handler/heartbeat_test.go
static/configs.go

This PR adds a handler for /v2/heartbeat/ requests.
- Upgrades the server connection to the WebSocket protocol.
- Starts a goroutine for reading messages.
- Sets a 30 second read deadline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/63)

Add /v2/heartbeat/ handler

---

handler/handler.go
handler/handler_test.go
handler/heartbeat_test.go
handler/monitoring_test.go
heartbeat/location.go
heartbeat/location_test.go
locate.go
locatetest/locatetest.go
locatetest/locatetest_test.go
openapi.yaml
static/configs.go

Note: A lot of the line count is due to refactoring and tests, not necessarily new functionality. That said, I'm happy to try to break this down if need be.
________
This PR adds a handler for "/v2beta/nearest" requests.
The OpenAPI configuration can be seen [here](https://api-portal.mlab-sandbox.measurementlab.net/docs/locate-dot-mlab-sandbox.appspot.com/2/introduction).
It also updates the static configuration to use half the [circumference](https://en.wikipedia.org/wiki/Earth%27s_circumference) of the earth (not half the diameter) as the max distance.
Example:
```
Request: https://locate-dot-mlab-sandbox.appspot.com/v2beta/nearest/ndt/ndt7?machine-type=virtual&api_key={API_KEY}
{
"results": [
{
"machine": "mlab1-lax0t.mlab-sandbox.measurement-lab.org",
"location": {
"city": "Los …
```

Add a /v2beta/nearest handler using the V2 Locator

---

handler/handler.go
handler/heartbeat.go
metrics/metrics.go
metrics/metrics_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/77)

Add metric counter for Heartbeat requests

---

api/v2/api.go
api/v2/scanner.go
api/v2/scanner_test.go
cloudbuild/cloudbuild.yaml
handler/prometheus.go
handler/prometheus_test.go
heartbeat/heartbeat.go
heartbeat/heartbeat_test.go
heartbeat/heartbeattest/heartbeattest.go
heartbeat/location.go
heartbeat/location_test.go
memorystore/client.go
memorystore/client_test.go

This PR adds functionality to save the Prometheus health signals locally and in Memorystore. It uses those signals in its server selection algorithm.
Sample Memorystore entry including Prometheus field:
```
Registration
$471
{"City":"New York","CountryCode":"US","ContinentCode":"NA","Experiment":"ndt","Hostname":"ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org","Latitude":40.7667,"Longitude":-73.8667,"Machine":"mlab1","Metro":"lga","Project":"mlab-sandbox","Site":"lga0t","Type":"physical","Uplink":"10g","Services":{"ndt/ndt5":["ws://:3001/ndt_protocol","wss://:3010/ndt_protocol"],"ndt/ndt7":["ws:///ndt/v7/download","ws:///ndt/v7/upload","wss:///ndt/v7/download","wss:///ndt/v7/upload"]}}
$6
Health
$11
{"Score":1}
$10
Prometheus
$15
{"Health":true}**
```
Changes were tested by putting …

Add Prometheus health signals to server selection

---

heartbeat/heartbeat.go
heartbeat/heartbeat_test.go
metrics/metrics.go
metrics/metrics_test.go

This PR adds two new metrics to determine healthy server counts.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/98)

Add metrics to determine server status

---

cloudbuild/cloudbuild.yaml

This PR updates the `-promote` flag in Cloudbuild to only be used in sandbox and staging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/103)

Make the promotion to the latest version conditional

---

cloudbuild/app.yaml.template

This PR reverts the cool down period to 5 mins.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/110)

Revert cool down period

---

cloudbuild/cloudbuild.yaml

This PR re-enables the `--promote` flag for the mlab-ns project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/113)

Reenable --promote for mlab-ns

---

connection/connection.go
metrics/metrics.go
metrics/metrics_test.go

This PR adds a new metric to track the number of re(connection) attempts from the HBS to the Locate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/119)

Add reconnection metrics

---

heartbeat/location.go
heartbeat/location_test.go

This PR addresses https://github.com/m-lab/locate/issues/142.
Tested using https://locate-dot-mlab-sandbox.appspot.com/v2/nearest/ndt/ndt7?site=lga1t (0.5 probability).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/148)

Ignore site probability when site parameter is passed

---

handler/handler.go
handler/handler_test.go

See https://github.com/m-lab/locate/issues/149 for details.
Tested by changing the user agent string to my own:
- Limited (13:00 UTC):
- Allowed (13:10 UTC):
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/162)

Rate limit requests for integration sending too many periodic requests

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/171)

Update coveralls target to travis-pro

---

USAGE.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/183)

Add note about the strict parameter to USAGE.md

---

cmd/heartbeat/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/189)

Give precedence to -hostname-file

---

memorystore/client.go
memorystore/client_test.go

This PR adds a function to delete by key to the memorystore package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/190)

Adds Del(key) to memorystore package

---

heartbeat/heartbeat.go

Follow-up to https://github.com/m-lab/locate/pull/199.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/201)

Add logging for errors writing Prometheus message to Memorystore

---

cloudbuild/cloudbuild.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/213)

Do not automatically promote after deployment in mlab-ns

---

handler/handler.go
handler/handler_test.go

This PR actually enables rate limiting. After looking at the first hours of results from the previous deployment with @mattmathis, we concluded that the clients identified exhibit clearly abusive usage patterns and it's safe to start blocking them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/214)

Enable rate limiting

---

handler/handler.go
metrics/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/216)

Add metric to track rate-limited clients by client_name

---

cloudbuild/app.yaml.mlab-ns.template
cloudbuild/app.yaml.template
cloudbuild/cloudbuild.yaml

This makes `-rate-limit-interval` and `-rate-limit-max` configurable via env variables in Cloud Build triggers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/217)

Make rate limiter parameters configurable via CB

---

cloudbuild/cloudbuild.yaml

Container Registry is being retired.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/locate/218)

Updates Cloud Build to use Artifact Registry container images
